Document compatibility between declarative and procedural macro tokens
rust-lang/reference pull request #1169
Opened 2022-02-15 10:38 UTC by petrochenkov

This PR assumes https://github.com/rust-lang/rust/pull/92472 is merged.

2022-02-15 10:38 UTC, petrochenkov commented on src/procedural-macros.md
> +    - `tt` and `ident` substitutions are never wrapped into such groups and
The `ident` part here requires https://github.com/rust-lang/rust/pull/92472.

2022-02-15 13:00 UTC, dtolnay requested changes

2022-02-15 13:00 UTC, dtolnay commented on src/procedural-macros.md
> +When passed from a proc macro
I suggest "When emitted from a proc macro" or "When returned by a proc macro". It's passing in a sense, but this isn't the clearest way to say that.

2022-03-31 14:27 UTC, petrochenkov commented
I've addressed review comments.
https://github.com/rust-lang/rust/pull/92472 has also landed.

2022-03-31 14:27 UTC, petrochenkov commented
@rustbot ready
(Is the bot working on this repo?)

2022-03-31 14:28 UTC, petrochenkov commented
@rustbot label +S-waiting-on-review

2022-03-31 20:05 UTC, ehuss reviewed
Thanks!

2022-03-31 21:14 UTC, petrochenkov commented on src/procedural-macros.md
> +  but not `+=`), and also the single quote `'` character
I languages defined by proc macros `'` is an independent token, it doesn't necessarily have to be joined with identifiers to form lifetimes.

2022-03-31 21:15 UTC, petrochenkov commented
I've added the changes from https://github.com/rust-lang/reference/pull/1169#discussion_r839962540 and https://github.com/rust-lang/reference/pull/1169#discussion_r839968049 in a slightly reworded form.

2022-04-01 23:33 UTC, ehuss approved these changes
Thanks!

2022-04-01 23:33 UTC, merged