Add spec identifiers to dynamically-sized-types.md
rust-lang/reference pull request #1582
Opened 2024-08-22 01:25 UTC by chorman0773

This adds spec identifier syntax to dynamically-sized-types.md

2024-10-17 23:49 UTC, traviscross requested changes, later dismissed

2024-10-17 23:49 UTC, traviscross commented on src/dynamically-sized-types.md
> +r[dynamic-sized-types]
This one is inconsistent from the ones that follow.

2024-12-11 23:53 UTC, chorman0773 commented
@rustbot ready

2025-01-07 16:30 UTC, ehuss approved these changes
Thanks!

2025-01-07 16:34 UTC, merged