Clarify that ::foo paths are not necessarily based off of the "crate root"
rust-lang/reference pull request #974
Opened 2021-03-07 21:07 UTC by Manishearth

Part of https://github.com/rust-lang/rust/issues/82876

2021-03-07 21:09 UTC, CryZe commented on src/paths.md
> +> Beginning with the 2018 Edition, paths starting with `::` resolve from from
```suggestion
> Beginning with the 2018 Edition, paths starting with `::` resolve from
```

2021-03-08 06:08 UTC, Havvy requested changes

2021-03-08 06:08 UTC, Havvy commented on src/paths.md
> +Paths starting with `::` are considered to be "global paths" where the segments of the path
```suggestion
Paths starting with `::` are considered to be *global paths* where the segments of the path
```

2021-03-08 06:08 UTC, Havvy commented on src/paths.md
> +> crates in the [extern prelude], i.e. they _must_ be followed by the name of a crate.
```suggestion
> crates in the [extern prelude]. That is, they must be followed by the name of a crate.
```

Trying to keep italics for defining terms, not for emphasizing specific words. If you think we absolutely **must** emphasize the word, we could make it bold, but I don't think we do.

2021-03-08 06:17 UTC, Havvy requested changes
Also, I think the default is to describe the currentmost edition's behavior outside of the edition differences section and specify how it's different in older in the edition differences section. So the part that is in the "Beginning with the 2018 edition" should be the description of what a global path is.

2021-03-08 13:35 UTC, ehuss commented
>  I think the default is to describe the currentmost edition's behavior outside of the edition differences section

I don't think this issue has been settled (see #698). The original intent was to have the main text describe what is common in both editions, and to use sidebars to explain where it diverges (with exceptions like the async chapters).  I'm starting to lean a little more towards preferring the "describe latest edition" approach, but there are some places where it can be a little awkward. 

Maybe @Manishearth has an opinion on which approach seems better overall?

(BTW, thanks for the PR, I kinda made a mess on this section.)

2021-03-08 16:06 UTC, Manishearth commented
When I wrote this PR I thought about it and decided not to because it was the reference, but I don't mind doing it. I did find it _easier_ to describe what it _was_ (a "global path") and then describe edition differences in a clear mirrored fashion.

2021-03-09 07:22 UTC, Havvy approved these changes

2021-03-09 07:24 UTC, merged

2021-03-09 07:27 UTC, Havvy commented
💟 Thanks!

I still prefer the idea of documenting the current edition as primary, but that can be redecided on elsewhere. The whole await/async thing might actually be in a better spot if `k#keywords` become a thing.